Repository Judge-Girl/Judge-Girl-CMS, pull requests merged in 2021-09, with the labels that each got.

#183 Dev/182 New Problem Editor: Markdown Update.
  package.json
  src/app/exam/questions/ExamQuestions.js
  src/app/problem/commons/MarkdownEditor.js
  src/app/problem/commons/MarkdownEditorPreviewTab.js
  src/app/problem/commons/MarkdownEditorWriteTab.js
  src/app/problem/editor/ProblemEditor.scss
  src/app/problem/editor/left/leftbar.scss
  src/app/problem/editor/right/Description.js
  src/app/problem/editor/right/ProvidedCodeItems.js
Labels: enhancement

#188 Dev/186 New Markdown Editor: Bugs in ExamQuestions.
  src/app/commons/modals/ModalInput.js
  src/app/commons/titles/TitleLine.js
  src/app/exam/ExamInPageNavigationBar.js
  src/app/exam/ExamList.js
  src/app/exam/ExamList.scss
  src/app/exam/modals/AddQuestionModal.js
  src/app/exam/options/ExamName.js
  src/app/exam/options/ExamOptions.js
  src/app/exam/options/ExamOptions.scss
  src/app/exam/participants/Examinees.js
  src/app/exam/questions/ExamDescription.js
  src/app/exam/questions/ExamDescription.scss
  src/app/exam/questions/ExamQuestions.js
  src/app/exam/questions/ExamQuestions.scss
  src/app/exam/score/ExamScorePage.js
  src/app/exam/scoreboard/ExamScoreboardPage.js
  src/app/exam/submissions/ExamLiveSubmissions.js
  src/app/problem/ProblemList.js
  src/app/problem/ProblemList.scss
  src/app/problem/editor/ProblemEditor.js
  src/app/problem/editor/ProblemEditor.scss
  src/app/problem/editor/right/Block.js
  src/app/problem/editor/right/ProblemDescription.js
  src/app/problem/editor/right/ProblemTitle.js
  src/app/problem/editor/right/RightBar.js
  src/app/problem/editor/right/Visible.js
  src/services/ExamService.js
Labels: bug

#162 [UI] Homework page #140
  src/app/homework/HomeworkList.js
  src/app/homework/HomeworkPageNavigationBar.js
  src/app/homework/progress/HomeworkContext.js
  src/app/homework/progress/HomeworkPage.scss
  src/app/homework/progress/HomeworkProgressPage.js
Labels: UI

#214 Dev/189 [UI] New Problem List
  package.json
  public/index.css
  src/app/commons/buttons/CreateButton.js
  src/app/problem/ProblemList.js
  src/app/problem/ProblemList.scss
  src/services/ProblemService.js
Labels: WIP
